### PR TITLE
Improved user handling

### PR DESCRIPTION
**Pull request by anjanms**
Added an option to fetch and add null users to the room
(I wish this wasn't needed, but plug occasionally doesn't send join events)

Added a function to get external users, also updates the internal object if the user is in the room

### CODE REVIEW

**Comment by thedark1337** [comment]
This issue is a plug.dj issue and has already been reported to them, they are actively looking into it.

**Comment by anjanms** [comment]
Yes, I'm aware it's their issue.  This problem has been coming and going since January or so.
I thought plugAPI should at least provide an option to use a similar band-aid like the web client does.

But if you don't want to accept this I understand, I'm not too happy with this "fix" either.
Though, what are your thoughts on the second function?

**Comment by thedark1337** [comment]
I'm not really sure if a getExternalUsers function is needed. It looks to me that all possible nulls are already handled via the other events in your pull request

**Comment by Hunchmun** [comment]
Hey, I thought I'd just chime in, on this,

I am the one actively pushing this to be fixed internally now, new guests are fine but the problem is existing users, the frontend doesn't have it right until they talk or whatever, which isn't good either.

I expect this issue to be fixed within the next week

**Comment by anjanms** [comment]
@Hunchmun Great, I'll be happy to see that finally resolved.

@thedark1337 That function is unrelated to the fix. My primary use for it would be to get the properties that aren't defined in _/rooms/state as needed.  Secondary use is to update a database row for a user that isn't in the room, if required.
But I'm not certain anyone else is doing anything like that, or using those properties even. I'll just continue patching it in myself.

**Pull request closed without merging**
