### PR TITLE
Do not assume we were given a valid array. Fixes #139

### LINKED ISSUE #139: 5.0.0 Crashes on joining the waitlist

### PR DESCRIPTION
**Pull request by mortenn**

### CODE REVIEW

**Comment by thedark1337** [comment]
Thanks for the bugfix to this, however you've got a trailing space on line 194. I'll merge once that is fixed :+1:

**Comment by Psykoral** [comment]
This fix is key! My bot keeps crashing to an invalid `id.length` and I need this fix in order to get past it. 

Can you push this into a 5.0.1 soon please?

**Comment by thedark1337** [comment]
I haven't had as much time as I used to for updating things. The current big issues that need to be fixed is playlist functionality and auto reconnect. After those two are fixed, I can release a 5.1.0 version.

**Comment by Psykoral** [comment]
I can certainly understand the lack of time, but in this case it's already done and checked in. I'm not sure I understand the hold up to be honest. You can simply release a "patch" version of `5.0.1` and then when you have your other items ready that you mentioned, you can release your "minor" version `5.1.0`.

Either way, we appreciate your work, but this bug makes the bots crash repeatedly, so a quick patch version would be amazing. Thanks!

**Comment by Hunchmun** [comment]
Until Alex pushes this as a patch, you should be able use the Github URL instead of the module name inside your package.json to fix this issue immediately, will that work in the interim?

**Comment by thedark1337** [comment]
The only issue with the latest "patches" i added to the master branch is auto reconnect crashing the bot sometimes. Other than that, it should relatively stable...  

For henchman's suggestion `npm i plugcubed/plugapi` would work (it'll pull from the git repo)

**Comment by Psykoral** [comment]
yeah, it'll work in the meantime. Just didn't know what the hold up was for a patch version with this fix in it is all. Thanks.

**Pull request merged**
